os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - python -m pip install --upgrade pip
script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests;fi'
branches:
  only:
    - main
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
jobs:
  include:
    - stage: Unit Test
      script: python -m unittest tests.test_dice
    - stage: Deploy to Staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: salty-fjord-84835
        api_key: $HEROKU_AUTH_TOKEN
    - stage: Test Staging
      script: 'curl https://salty-fjord-84835.herokuapp.com/'
    - stage: Deploy to Production
      script: skip
      deploy:
        <<: *heroku
        app: pacific-mountain-30651
    - stage: Test Production
      script: 'curl http://pacific-mountain-30651.herokuapp.com'